// Share browser modules with Go; serve celld's mode-aware CLI clients. This compiler
// supports only the template expressions used by Mayfly, and fails on new ones.
import { readFile, readdir, writeFile } from "node:fs/promises";
import { nativeDocumentation } from "./documentation.mjs";
const read = name => readFile(new URL(`../srv/${name}`, import.meta.url), "utf8");
const files = {};
for (const dir of ["docs", "browser", "templates", "static"]) {
  for (const name of (await readdir(new URL(`../srv/${dir}/`, import.meta.url))).sort()) {
    if (name.includes(".") && name !== "README.md") files[`${dir}/${name}`] = await read(`${dir}/${name}`);
  }
}
for (const name of await readdir(new URL("./static/", import.meta.url))) {
  files[`static/${name}`] = await readFile(new URL(`./static/${name}`, import.meta.url), "utf8");
}
for (const dir of ['browser', 'templates']) {
  for (const name of await readdir(new URL(`./${dir}/`, import.meta.url))) files[`${dir}/${name}`] = await readFile(new URL(`./${dir}/${name}`, import.meta.url), 'utf8');
}
const spacesClient = '#!/usr/bin/env node\n// Generated by celld/generate.mjs. Node 22+, no dependencies.\n' + files['browser/spaces.js'] + '\n' + await readFile(new URL('./clients/spaces.mjs', import.meta.url), 'utf8');
const spacesPath = new URL('./static/spaces.mjs', import.meta.url);
if (process.argv.includes('--check')) {
  if (await readFile(spacesPath, 'utf8') !== spacesClient) throw new Error('Generated spaces client is stale: run npm run generate');
} else await writeFile(spacesPath, spacesClient);
files['static/spaces.mjs'] = spacesClient;
const partials = {};
for (const file of ["site.html", "view.css.html"]) {
  for (const match of files[`templates/${file}`].matchAll(/{{define "([^"]+)"}}([\s\S]*?){{end}}/g)) partials[match[1]] = match[2];
}
const templates = {};
for (const name of ["index", "view", "gone", "doc", "wiki"]) {
  let source = files[`templates/${name}.html`].replace(/{{template "([^"]+)"(?: \.)?}}/g, (_, key) => {
    if (!(key in partials)) throw new Error(`Unknown partial: ${key}`);
    return partials[key];
  });
  source = source.replace('const EXPIRES_AT = {{.ExpiresAt}};', 'const EXPIRES_AT = {{.ExpiresAtJSON}};');
  source = source.replace('{{if not .ExpiresAt}} hidden{{end}}', '{{.ExpiresHidden}}');
  if (['index','view','wiki'].includes(name)) source = source.replace('</head>', '<style nonce="{{.CSPNonce}}">'+files['browser/spaces.css']+'</style></head>');
  if (['view','wiki'].includes(name)) {
    source = source.replace('</head>', '<style nonce="{{.CSPNonce}}">'+files['browser/media.css']+'</style><script nonce="{{.CSPNonce}}">{{browser "text-preview.js"}}\n{{browser "clipboard.js"}}\n{{browser "media.js"}}</script></head>');
    source = source.replace('<body', '<body data-ai-summary="{{.SummaryEnabled}}"');
    source = source.replace('</head>', '<style nonce="{{.CSPNonce}}">'+files['browser/summary.css']+'</style></head>');
    source = source.replace('</body>', '<script nonce="{{.CSPNonce}}">{{browser "summary.js"}}</script></body>');
  }
  if (name === 'index') {
    source = source.replace('<a id="newbtn"', '<div id="paired-creation" class="space-options"{{.WikiHidden}}><label><input id="create-with-wiki" type="checkbox"> Create a linked wiki</label><div id="create-wiki-options" hidden><label>Wiki title<input id="create-wiki-title" type="text" value="Shared wiki" maxlength="160"></label><p class="meta">Anyone with either complete link can access both. The wiki stays after the chat expires.</p></div></div>\n<a id="newbtn"');
    source = source.replace('<p id="status"', '<p{{.WikiHidden}}><a id="newwikibtn" class="button" href="/wiki">New wiki ↗</a></p><div id="creation-recovery" class="space-recovery"></div>\n<p id="status"');
    source = source.replace('{{browser "index.js"}}', '{{browser "spaces.js"}}\n{{browser "spaces-ui.js"}}\n{{browser "index.js"}}');
  }
  if (name === 'view') {
    source = source.replace('<div id="log">', '<div{{.WikiHidden}}><section id="companions" class="companions" aria-label="Linked wikis" hidden></section></div>\n<div id="log">');
    source = source.replace('{{browser "view.js"}}', '{{browser "view.js"}}\n{{browser "spaces.js"}}\n{{browser "spaces-ui.js"}}');
    source = source.replace('>init();</script>', '>init(); mayflyCompanions(location.href,document.getElementById("companions"));</script>');
  }
  if (name === "index" || name === "view") {
    source = source.replace('const VECTORS = {{.Vectors}};', 'const MAYFLY_CONFIG = {{.SettingsJSON}};\nconst VECTORS = {{.Vectors}};');
    source = source.replace('<p id="status"', '<p id="privacy" class="meta">{{.PrivacyText}}</p>\n<p id="status"');
    if (name === "view") source = source.replace('<div id="nokey"', '<p id="privacy" class="meta">{{.PrivacyText}}</p>\n<div id="nokey"');
  }
  const allowed = new Set(["CSPNonce", "Channel.ID", "RetentionMS", "ExpiresAt", "ExpiresAtJSON", "ExpiresHidden", "RetentionText", "Title", "Source", "SettingsJSON", "PrivacyText", "WikiHidden", "WikiID", "WikiLayout", "SummaryEnabled"]);
  // Split before injecting scripts: braces in trusted JavaScript are literal.
  const parts = [];
  let start = 0;
  for (const match of source.matchAll(/{{([\s\S]*?)}}/g)) {
    parts.push(source.slice(start, match.index));
    const expr = match[1];
    const browser = /^browser "([^"]+)"$/.exec(expr);
    if (browser) parts.push(files[`browser/${browser[1]}`]);
    else if (expr === ".Vectors") parts.push(files["static/vectors.json"]);
    else if (expr === ".MarkedJS") parts.push(await read("static/vendor/marked.umd.js"));
    else if (expr === ".PurifyJS") parts.push(await read("static/vendor/purify.js"));
    else if (expr.startsWith(".") && allowed.has(expr.slice(1))) parts.push({ field: expr.slice(1) });
    else throw new Error(`Unsupported template expression: ${expr}`);
    start = match.index + match[0].length;
  }
  parts.push(source.slice(start));
  // Collapse adjacent literal chunks to keep the generated bundle compact.
  templates[name] = parts.reduce((out, part) => {
    if (typeof part === "string" && typeof out.at(-1) === "string") out[out.length - 1] += part;
    else out.push(part);
    return out;
  }, []);
}
const staticFiles = await nativeDocumentation(Object.fromEntries(Object.entries(files).sort(([a], [b]) => a.localeCompare(b)).filter(([key]) => /^(docs\/|static\/(?:client\.|create\.|(?:wiki|spaces)\.mjs$|emoji\.txt$))/.test(key))));
const instructions = (await read("instructions.go")).match(/return fmt\.Sprintf\(`([\s\S]*?)`, base, channelID, name, retentionText\)/)?.[1];
if (!instructions) throw new Error("Instructions format changed");
const output = `// Generated by celld/generate.mjs; edit srv/browser, celld/static, or the source templates/docs.\nexport const templates = ${JSON.stringify(templates)};\nexport const staticFiles: Record<string, string> = ${JSON.stringify(staticFiles)};\nexport const instructions = ${JSON.stringify(instructions)};\n`;
const destination = new URL("./native/assets.generated.ts", import.meta.url);
if (process.argv.includes("--check")) {
  if (await readFile(destination, "utf8") !== output) throw new Error("Generated assets are stale: run npm run generate");
} else await writeFile(destination, output);
