// Share browser modules with Go; serve celld's mode-aware CLI clients. This compiler
// supports only the template expressions used by Mayfly, and fails on new ones.
import { readFile, readdir, writeFile } from "node:fs/promises";
import { nativeDocumentation } from "./documentation.mjs";
const read = name => readFile(new URL(`../srv/${name}`, import.meta.url), "utf8");
const files = {};
for (const dir of ["docs", "browser", "templates", "static"]) {
  for (const name of (await readdir(new URL(`../srv/${dir}/`, import.meta.url))).sort()) {
    if (name.includes(".") && name !== "README.md") files[`${dir}/${name}`] = await read(`${dir}/${name}`);
  }
}
for (const name of await readdir(new URL("./static/", import.meta.url))) {
  files[`static/${name}`] = await readFile(new URL(`./static/${name}`, import.meta.url), "utf8");
}
const partials = {};
for (const file of ["site.html", "view.css.html"]) {
  for (const match of files[`templates/${file}`].matchAll(/{{define "([^"]+)"}}([\s\S]*?){{end}}/g)) partials[match[1]] = match[2];
}
const templates = {};
for (const name of ["index", "view", "gone", "doc"]) {
  let source = files[`templates/${name}.html`].replace(/{{template "([^"]+)"(?: \.)?}}/g, (_, key) => {
    if (!(key in partials)) throw new Error(`Unknown partial: ${key}`);
    return partials[key];
  });
  source = source.replace('const EXPIRES_AT = {{.ExpiresAt}};', 'const EXPIRES_AT = {{.ExpiresAtJSON}};');
  source = source.replace('{{if not .ExpiresAt}} hidden{{end}}', '{{.ExpiresHidden}}');
  if (name === "index" || name === "view") {
    source = source.replace('const VECTORS = {{.Vectors}};', 'const MAYFLY_CONFIG = {{.SettingsJSON}};\nconst VECTORS = {{.Vectors}};');
    source = source.replace('<p id="status"', '<p id="privacy" class="meta">{{.PrivacyText}}</p>\n<p id="status"');
    if (name === "view") source = source.replace('<div id="nokey"', '<p id="privacy" class="meta">{{.PrivacyText}}</p>\n<div id="nokey"');
  }
  const allowed = new Set(["CSPNonce", "Channel.ID", "RetentionMS", "ExpiresAt", "ExpiresAtJSON", "ExpiresHidden", "RetentionText", "Title", "Source", "SettingsJSON", "PrivacyText"]);
  // Split before injecting scripts: braces in trusted JavaScript are literal.
  const parts = [];
  let start = 0;
  for (const match of source.matchAll(/{{([\s\S]*?)}}/g)) {
    parts.push(source.slice(start, match.index));
    const expr = match[1];
    const browser = /^browser "([^"]+)"$/.exec(expr);
    if (browser) parts.push(files[`browser/${browser[1]}`]);
    else if (expr === ".Vectors") parts.push(files["static/vectors.json"]);
    else if (expr === ".MarkedJS") parts.push(await read("static/vendor/marked.umd.js"));
    else if (expr === ".PurifyJS") parts.push(await read("static/vendor/purify.js"));
    else if (expr.startsWith(".") && allowed.has(expr.slice(1))) parts.push({ field: expr.slice(1) });
    else throw new Error(`Unsupported template expression: ${expr}`);
    start = match.index + match[0].length;
  }
  parts.push(source.slice(start));
  // Collapse adjacent literal chunks to keep the generated bundle compact.
  templates[name] = parts.reduce((out, part) => {
    if (typeof part === "string" && typeof out.at(-1) === "string") out[out.length - 1] += part;
    else out.push(part);
    return out;
  }, []);
}
const staticFiles = await nativeDocumentation(Object.fromEntries(Object.entries(files).filter(([key]) => /^(docs\/|static\/(?:client\.|create\.|emoji\.txt$))/.test(key))));
const instructions = (await read("instructions.go")).match(/return fmt\.Sprintf\(`([\s\S]*?)`, base, channelID, name, retentionText\)/)?.[1];
if (!instructions) throw new Error("Instructions format changed");
const output = `// Generated by celld/generate.mjs; edit srv/browser, celld/static, or the source templates/docs.\nexport const templates = ${JSON.stringify(templates)};\nexport const staticFiles: Record<string, string> = ${JSON.stringify(staticFiles)};\nexport const instructions = ${JSON.stringify(instructions)};\n`;
const destination = new URL("./native/assets.generated.ts", import.meta.url);
if (process.argv.includes("--check")) {
  if (await readFile(destination, "utf8") !== output) throw new Error("Generated assets are stale: run npm run generate");
} else await writeFile(destination, output);
