import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import { execute, page, post, wikiHarness } from './wiki-test-helper.mjs';

test('real browser downloads attachments and plays fullscreen video in wiki and chat', {timeout:120000}, async t=>{
  assert.ok(process.env.CHROME_BIN,'Set CHROME_BIN for the media browser test');
  const h=await wikiHarness(t,{WIKI_BOOK_LAYOUT_ENABLED:'1'}), wiki=await h.create('Media workshop');
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+ip1sAAAAASUVORK5CYII=','base64');
  const videoPath=join(h.directory,'clip.mp4'), imagePath=join(h.directory,'diagram.png'), jpegPath=join(h.directory,'still.jpg'), svgPath=join(h.directory,'vector.svg'), htmlPath=join(h.directory,'notes.html'), textPath=join(h.directory,'meeting notes.txt');
  await execute('ffmpeg',['-v','error','-f','lavfi','-i','color=c=0xc98360:s=160x90:d=2','-an','-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',videoPath]);
  await execute('ffmpeg',['-v','error','-i',videoPath,'-frames:v','1',jpegPath]);
  const video=await readFile(videoPath), unsafe='<script>window.unsafeMedia=true</script>', note='Human attachment: retain the exact bytes.\n', pdf='%PDF-1.7\nExternal download fixture\n';
  await writeFile(imagePath,png);await writeFile(htmlPath,unsafe);await writeFile(textPath,note);
  const client=join(h.directory,'wiki.mjs');await writeFile(client,(await h.http('/static/wiki.mjs')).body);
  const upload=async file=>JSON.parse((await execute(process.execPath,[client,'upload',wiki.url,file])).stdout);
  const imageFile=await upload(imagePath), videoFile=await upload(videoPath), htmlFile=await upload(htmlPath), jpegFile=await upload(jpegPath);
  for(const file of [imageFile,videoFile,htmlFile])assert.ok(file.id,JSON.stringify(file));
  const externalRequests=[];
  const external=createServer((req,res)=>{
    externalRequests.push({path:req.url,authorization:req.headers.authorization,referer:req.headers.referer});
    if(req.url==='/clip.mp4')res.writeHead(200,{'Content-Type':'video/mp4','Content-Length':video.length}).end(video);
    else if(req.url==='/guide.pdf')res.writeHead(200,{'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="guide.pdf"'}).end(pdf);
    else res.writeHead(200,{'Content-Type':'image/png'}).end(png);
  });
  await new Promise(resolve=>external.listen(0,'127.0.0.1',resolve));
  t.after(()=>new Promise(resolve=>{external.closeAllConnections();external.close(resolve);}));
  const externalBase='http://127.0.0.1:'+external.address().port;
  const svg='<svg xmlns="http://www.w3.org/2000/svg" width="24" height="16" onload="parent.unsafeMedia=true"><script>parent.unsafeMedia=true</script><image href="'+externalBase+'/svg-track.png" width="1" height="1"/><rect width="24" height="16" fill="red"/></svg>';
  await writeFile(svgPath,svg);const svgFile=await upload(svgPath);
  assert.equal(svgFile.type,'image/svg+xml');assert.match(svgFile.markdown,/^!\[/);
  const created=(await wiki.request('/pages',post(page('Media',[imageFile.markdown,videoFile.markdown,htmlFile.markdown,jpegFile.markdown,svgFile.markdown,'![unconsented]('+externalBase+'/never.png)','<video src="'+externalBase+'/raw.mp4"></video>'].join('\n\n'))))).body;
  const url=new URL(wiki.url);url.searchParams.set('page',created.id);
  const downloadPath=join(h.directory,'downloads');await mkdir(downloadPath);
  const capture=process.env.MAYFLY_MEDIA_CAPTURE_DIR;if(capture)await mkdir(capture,{recursive:true});
  const config={chrome:process.env.CHROME_BIN,profile:join(h.directory,'chrome'),base:h.base,url:url.href,externalBase,downloadPath,textPath,note,unsafe,svg,pdf,png:png.toString('base64'),video:video.toString('base64'),videoID:videoFile.id,htmlID:htmlFile.id,capture};
  let harness=await readFile(new URL('../srv/testdata/chrome.cjs',import.meta.url),'utf8');
  harness=harness.replace('const msg=JSON.parse(raw), p=pending.get(msg.id);', 'const msg=JSON.parse(raw); if(msg.method==="Network.requestWillBeSent") requests.push(msg.params.request); const p=pending.get(msg.id);');
  const exercise=String.raw`
const fs=require('node:fs'),path=require('node:path');
(async()=>{try{
  const {targetInfos}=await cdp('Target.getTargets');const tab=await attach(targetInfos.find(t=>t.type==='page').targetId);
  await cdp('Network.enable',{},tab.sessionId);
  await cdp('Browser.grantPermissions',{origin:config.base,permissions:['clipboardReadWrite','clipboardSanitizedWrite']});
  await cdp('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:config.downloadPath});
  await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1040,deviceScaleFactor:1,mobile:false},tab.sessionId);
  await cdp('Page.addScriptToEvaluateOnNewDocument',{source:'window.mediaErrors=[];window.mediaViolations=[];addEventListener("error",e=>{if(e.message)mediaErrors.push(e.message)});addEventListener("unhandledrejection",e=>mediaErrors.push(String(e.reason)));addEventListener("securitypolicyviolation",e=>mediaViolations.push(e.violatedDirective));'},tab.sessionId);
  // A headless browser has no OS share sheet: stub that boundary, retain real Files/gestures.
  await cdp('Page.addScriptToEvaluateOnNewDocument',{source:'window.sharedFiles=[];Object.defineProperty(navigator,"canShare",{configurable:true,value:data=>data.files?.length===1&&data.files[0].type==="video/mp4"});Object.defineProperty(navigator,"share",{configurable:true,value:async data=>{if(window.shareCanceled)throw new DOMException("Canceled","AbortError");const file=data.files[0];sharedFiles.push({name:file.name,type:file.type,active:navigator.userActivation.isActive,bytes:Array.from(new Uint8Array(await file.arrayBuffer()))})}});'},tab.sessionId);
  const card=name=>'[...document.querySelectorAll(".mayfly-media")].find(c=>c.querySelector(".media-name").textContent==='+JSON.stringify(name)+')';
  const click=async expression=>{
    await cdp('Page.bringToFront',{},tab.sessionId);
    await evaluate(tab,expression+'.scrollIntoView({block:"center"})');
    await evaluate(tab,'new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))');
    const box=await evaluate(tab,'(()=>{const e='+expression+';e.scrollIntoView({block:"center"});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()');
    await cdp('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...box},tab.sessionId);
    await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...box},tab.sessionId);
  };
  const downloaded=async(name,bytes)=>{
    const file=path.join(config.downloadPath,name);
    await until(()=>fs.existsSync(file)&&fs.readFileSync(file).equals(bytes),'download '+name);
  };
  const copyImage=async(name,width,height)=>{
    const root=card(name);
    await click(root+'.querySelector(".media-copy > summary")');await click(root+'.querySelector(".media-copy-image")');
    await until(()=>evaluate(tab,root+'.querySelector(".media-status").textContent.includes("Image copied")'),'image clipboard write '+name).catch(async error=>{console.error(await evaluate(tab,root+'.outerHTML'));throw error;});
    const copied=await evaluate(tab,'(async()=>{const [item]=await navigator.clipboard.read();const blob=await item.getType("image/png"),image=await createImageBitmap(blob);const result={type:blob.type,width:image.width,height:image.height};image.close();return result})()');
    assert.deepEqual(copied,{type:'image/png',width,height});
  };
  const readyVideo=()=>until(()=>evaluate(tab,'(()=>{const v=document.querySelector(".media-preview video");return v?.readyState>=1&&v.duration>0})()'),'video metadata').catch(async error=>{console.error(await evaluate(tab,'({cards:[...document.querySelectorAll(".mayfly-media")].map(e=>({name:e.querySelector(".media-name").textContent,status:e.querySelector(".media-status").textContent,video:e.querySelector("video")?.outerHTML})),errors:mediaErrors,csp:mediaViolations})'));throw error;});
  const capture=async name=>{if(config.capture){const {data}=await cdp('Page.captureScreenshot',{format:'png'},tab.sessionId);fs.writeFileSync(path.join(config.capture,name+'.png'),Buffer.from(data,'base64'));}};
  const fullscreen=async()=>{
    await click('document.querySelector(".media-fullscreen")');
    await until(()=>evaluate(tab,'document.fullscreenElement===document.querySelector(".media-preview video")'),'video entered fullscreen');
    await evaluate(tab,'document.exitFullscreen()');
    await until(()=>evaluate(tab,'!document.fullscreenElement'),'video left fullscreen');
  };
  await cdp('Page.navigate',{url:config.url},tab.sessionId);
  await until(()=>evaluate(tab,'document.querySelectorAll("#wiki-content .mayfly-media").length===6'),'wiki attachment cards');
  await until(()=>evaluate(tab,'document.querySelector("#wiki-content img")?.naturalWidth===1'),'owned image preview').catch(async error=>{console.error(await evaluate(tab,'({html:document.getElementById("wiki-content").innerHTML,errors:mediaErrors,csp:mediaViolations})'));throw error;});
  await until(()=>evaluate(tab,card('vector.svg')+'?.querySelector("img")?.naturalWidth===24'),'SVG image preview');
  assert.ok(await evaluate(tab,card('vector.svg')+'.querySelector("img").src.startsWith("data:image/svg+xml")'));
  assert.equal(await evaluate(tab,'window.unsafeMedia'),undefined);
  assert.ok(!requests.some(r=>r.url===config.externalBase+'/svg-track.png'),'SVG image does not load external resources');
  assert.equal(requests.filter(r=>r.method==='GET'&&r.url.includes('/attachments/'+config.videoID)).length,0,'no eager video bytes');
  await until(()=>evaluate(tab,card('notes.html')+'?.querySelector(".text-source code")?.textContent==='+JSON.stringify(config.unsafe)),'HTML source previews as inert text');
  assert.ok(!requests.some(r=>r.url.startsWith(config.externalBase)),'no automatic external media requests');
  await copyImage('diagram.png',1,1);await copyImage('still.jpg',160,90);await copyImage('vector.svg',24,16);
  await click(card('diagram.png')+'.querySelector(".media-download")');await downloaded('diagram.png',Buffer.from(config.png,'base64'));
  await click(card('notes.html')+'.querySelector(".media-download")');await downloaded('notes.html',Buffer.from(config.unsafe));
  assert.equal(await evaluate(tab,'window.unsafeMedia'),undefined);
  assert.equal(await evaluate(tab,'document.querySelectorAll("#wiki-content iframe,#wiki-content object").length'),0);
  await click(card('clip.mp4')+'.querySelector(".media-load")');await readyVideo();
  assert.equal(await evaluate(tab,card('clip.mp4')+'.querySelector(".media-copy")'),null,'videos do not claim clipboard file support');
  await click(card('clip.mp4')+'.querySelector(".media-share")');
  await until(()=>evaluate(tab,'sharedFiles.length===1'),'video handed to share API');
  const shared=await evaluate(tab,'sharedFiles[0]');
  assert.equal(shared.name,'clip.mp4');assert.equal(shared.type,'video/mp4');assert.equal(shared.active,true,'share retains user gesture');
  assert.deepEqual(Buffer.from(shared.bytes),Buffer.from(config.video,'base64'),'share preserves full MP4 bytes');
  await evaluate(tab,'window.shareCanceled=true');await click(card('clip.mp4')+'.querySelector(".media-share")');
  await until(()=>evaluate(tab,card('clip.mp4')+'.querySelector(".media-status").textContent==="Sharing canceled."'),'canceling share');
  assert.deepEqual(await evaluate(tab,'(()=>{const v=document.querySelector(".media-preview video");return {controls:v.controls,inline:v.playsInline,paused:v.paused}})()'),{controls:true,inline:true,paused:true});
  await cdp('Runtime.evaluate',{expression:'document.querySelector(".media-preview video").play()',userGesture:true,awaitPromise:true},tab.sessionId);
  await until(()=>evaluate(tab,'document.querySelector(".media-preview video").currentTime>.15'),'actual video playback');
  await evaluate(tab,'window.previousVideo=document.querySelector(".media-preview video");previousVideo.pause();previousVideo.currentTime=1');
  await until(()=>evaluate(tab,'previousVideo.paused&&previousVideo.currentTime>=1&&!previousVideo.seeking'),'pause and seek');
  await capture('wiki-desktop');
  await fullscreen();
  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},tab.sessionId);
  assert.ok(await evaluate(tab,'document.documentElement.scrollWidth<=innerWidth'),'mobile wiki width');
  await copyImage('diagram.png',1,1);
  await capture('wiki-mobile');
  await fullscreen();
  await click(card('clip.mp4')+'.querySelector(".media-download")');await downloaded('clip.mp4',Buffer.from(config.video,'base64'));
  assert.equal(requests.filter(r=>r.method==='GET'&&r.url.includes('/attachments/'+config.videoID)).length,1,'preview and download share authorized bytes');
  await evaluate(tab,'Object.defineProperty(navigator,"canShare",{configurable:true,value:()=>false})');
  await click('document.getElementById("wiki-edit")');
  const {root}=await cdp('DOM.getDocument',{},tab.sessionId);
  const {nodeId}=await cdp('DOM.querySelector',{nodeId:root.nodeId,selector:'#wiki-upload'},tab.sessionId);
  await cdp('DOM.setFileInputFiles',{nodeId,files:[config.textPath]},tab.sessionId);
  await until(()=>evaluate(tab,'document.getElementById("wiki-markdown").value.includes("meeting notes.txt")'),'human attachment inserted');
  await click('document.querySelector("#wiki-editor button[type=submit]")');
  await until(()=>evaluate(tab,'!!'+card('meeting notes.txt')),'human attachment saved');
  assert.ok(await evaluate(tab,'previousVideo.paused&&!previousVideo.isConnected'),'leaving a page stops its video');
  await until(()=>evaluate(tab,card('meeting notes.txt')+'?.querySelector("code")?.textContent==='+JSON.stringify(config.note.trimEnd())),'human text preview ready');
  await until(()=>evaluate(tab,card('notes.html')+'?.querySelector("code")?.textContent==='+JSON.stringify(config.unsafe)),'preceding text preview ready');
  await until(()=>evaluate(tab,card('diagram.png')+'?.querySelector("img")?.naturalWidth===1'),'preceding image ready after save');
  await click(card('clip.mp4')+'.querySelector(".media-load")');await readyVideo();
  assert.ok(await evaluate(tab,card('clip.mp4')+'.querySelector(".media-share").hidden'),'unsupported file sharing stays hidden');
  await click(card('meeting notes.txt')+'.querySelector(".media-download")');await downloaded('meeting notes.txt',Buffer.from(config.note));
  assert.deepEqual(await evaluate(tab,'mediaErrors'),[]);assert.deepEqual(await evaluate(tab,'mediaViolations'),[]);
  console.log('PASS wiki: actual PNG/JPEG clipboard, full MP4 share API handoff/cancel/unsupported fallback, exact downloads, playback and fullscreen on desktop/mobile');
  await cdp('Page.navigate',{url:config.base+'/'},tab.sessionId);
  await until(()=>evaluate(tab,'typeof newChannel==="function"'),'chat creation');await click('document.getElementById("newbtn")');
  await until(()=>evaluate(tab,'!!document.getElementById("compose")&&!document.getElementById("main").hidden'),'chat ready');
  const chatURL=await evaluate(tab,'location.href');
  const message='![Chat image]('+config.externalBase+'/photo.png)\n\n[Chat video]('+config.externalBase+'/clip.mp4)\n\n[Chat document]('+config.externalBase+'/guide.pdf)\n\n<script>window.unsafeMedia=true</script>\n\n[bad](javascript:alert(1))';
  await evaluate(tab,'document.getElementById("text").value='+JSON.stringify(message)+';document.getElementById("compose").requestSubmit()');
  await until(()=>evaluate(tab,'document.querySelectorAll("#log .mayfly-media").length===3'),'chat media delivered');
  assert.equal(await evaluate(tab,'document.querySelectorAll("#log .media-copy,#log .media-share").length'),0,'external files remain download/open controls');
  assert.ok(!requests.some(r=>r.url.startsWith(config.externalBase)),'chat media remains opt-in');
  await click(card('Chat image')+'.querySelector(".media-load")');
  await until(()=>evaluate(tab,'document.querySelector("#log img")?.naturalWidth===1'),'chat image loaded');
  await click(card('Chat video')+'.querySelector(".media-load")');await readyVideo();await fullscreen();
  await cdp('Runtime.evaluate',{expression:'document.querySelector(".media-preview video").play()',userGesture:true,awaitPromise:true},tab.sessionId);
  await until(()=>evaluate(tab,'document.querySelector(".media-preview video").currentTime>.15'),'external chat video plays');
  await evaluate(tab,'document.querySelector(".media-preview video").pause()');
  await capture('chat-mobile');
  await click(card('Chat document')+'.querySelector(".media-download")');await downloaded('guide.pdf',Buffer.from(config.pdf));
  assert.equal(await evaluate(tab,'location.href'),chatURL,'download preserves the chat');
  assert.ok(await evaluate(tab,'document.documentElement.scrollWidth<=innerWidth'),'mobile chat width');
  assert.equal(await evaluate(tab,'window.unsafeMedia'),undefined);
  assert.deepEqual(await evaluate(tab,'mediaErrors'),[]);assert.deepEqual(await evaluate(tab,'mediaViolations'),[]);
  console.log('PASS chat: opt-in external image/video, playback and fullscreen, file download, mobile layout and CSP');
}finally{chrome.kill('SIGTERM');await exited;}})().catch(error=>{console.error(error);process.exitCode=1;});`;
  const script=join(h.directory,'media.cjs');await writeFile(script,'const config='+JSON.stringify(config)+';\nconst requests=[];\n'+harness+'\n'+exercise);
  try {const {stdout}=await execute(process.execPath,[script],{timeout:90000,maxBuffer:1024*1024});t.diagnostic(stdout);}
  catch(error){throw new Error((error.stdout||'')+(error.stderr||error.message));}
  assert.ok(externalRequests.some(r=>r.path==='/clip.mp4'));
  assert.ok(externalRequests.every(r=>!r.authorization&&!r.referer),'no app credentials or referrers reach external media');
  assert.ok(!externalRequests.some(r=>r.path==='/never.png'||r.path==='/raw.mp4'));
});
