import assert from 'node:assert/strict';
import { readFile,writeFile,mkdir } from 'node:fs/promises';
import { randomBytes } from 'node:crypto';
import { join } from 'node:path';
import test from 'node:test';
import { MayflySpaces as spaces } from './static/spaces.mjs';
import { execute,page,post } from './wiki-test-helper.mjs';
import { summaryHarness } from './summary-test-helper.mjs';

for(const layout of ['book','classic'])test('chat, page and wiki summaries stream in desktop and mobile Chrome ('+layout+')', {timeout:60000}, async t=>{
  assert.ok(process.env.CHROME_BIN,'Set CHROME_BIN to run the browser test');
  const h=await summaryHarness(t,{WIKI_BOOK_LAYOUT_ENABLED:layout==='book'?'1':'0'}),wiki=await h.create('Release handbook');
  const first=(await wiki.request('/pages',post(page('Release plan','# Release plan\n\n## Decision\nShip a small release on Friday.\n\n## Next step\nVerify the result together.')))).body;
  await wiki.request('/pages',post(page('Runbook','# Runbook\n\n## Verification\nCheck the release and document its outcome.')));
  const created=await spaces.complete(await spaces.plan(h.base,{chat:true})),chat=await spaces.capability(created.chat_url);
  const posted=await h.http(chat.path+'/events?last=-1',{...post({nonce:randomBytes(12).toString('base64url'),from:'human',text:'Let us ship on Friday and verify the result.'}),headers:{'Content-Type':'application/json',Authorization:'Bearer '+chat.auth}});assert.equal(posted.status,200);
  const config={chrome:process.env.CHROME_BIN,profile:join(h.directory,'chrome'),wiki:wiki.url.replace('#','?page='+first.id+'#'),chat:chat.url,page:first.id,layout,control:h.summaryControl,capture:layout==='book'?process.env.SUMMARY_CAPTURE_DIR||null:null};
  if(config.capture)await mkdir(config.capture,{recursive:true});
  const harness=await readFile(new URL('../srv/testdata/chrome.cjs',import.meta.url),'utf8');
  const exercise=String.raw`
async function control(value={}){return (await fetch(config.control,{method:'POST',body:JSON.stringify(value)})).json();}
(async()=>{try{
 const {targetInfos}=await cdp('Target.getTargets'),tab=await attach(targetInfos.find(t=>t.type==='page').targetId);
 await cdp('Page.addScriptToEvaluateOnNewDocument',{source:"window.testErrors=[];window.testViolations=[];window.addEventListener('error',e=>testErrors.push(e.message));window.addEventListener('unhandledrejection',e=>testErrors.push(String(e.reason)));window.addEventListener('securitypolicyviolation',e=>testViolations.push(e.violatedDirective));"},tab.sessionId);
 const click=selector=>evaluate(tab,'document.querySelector('+JSON.stringify(selector)+').click()');
 const text=id=>evaluate(tab,'document.getElementById('+JSON.stringify(id)+').textContent');
 const complete=()=>until(async()=>await text('ai-summary-state')==='Summary complete.','summary complete');
 const writing=()=>until(async()=>(await text('ai-summary-output')).includes('Résumé 🐝'),'first streamed text');
 const capture=async name=>{if(!config.capture)return;const shot=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false},tab.sessionId);require('node:fs').writeFileSync(require('node:path').join(config.capture,name+'.png'),Buffer.from(shot.data,'base64'));};
 await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1040,deviceScaleFactor:1,mobile:false},tab.sessionId);
 await cdp('Page.navigate',{url:config.wiki},tab.sessionId);
 await until(()=>evaluate(tab,'!!document.getElementById("wiki-summary-page") && !document.getElementById("wiki-summary-page").disabled'),'page summary button');
 assert.equal((await control()).requests,0,'opening a resource never calls the model');
 if(config.layout==='book')assert.equal(await evaluate(tab,'document.getElementById("wiki-book-search").parentElement.id'),'wiki-header');
 const before=await text('wiki-content');
 await control({hold:true});await click('#wiki-summary-page');await writing();
 assert.equal(await evaluate(tab,'document.getElementById("ai-summary-dialog").dataset.busy'),'true');
 assert.equal(await evaluate(tab,'document.querySelector(".ai-summary-actions button:last-child").disabled'),true);
 assert.equal((await control()).finished,0,'visible output arrives before completion');
 assert.equal(await evaluate(tab,'getComputedStyle(document.querySelector(".ai-summary-piece")).animationName'),'ai-summary-reveal');
 assert.ok((await text('ai-summary-coverage')).includes('1 of 1 page'));
 await capture('summary-desktop-streaming');
 await control({release:true,hold:false});await complete();
 assert.equal(await evaluate(tab,'document.querySelectorAll("#ai-summary-output script,#ai-summary-output img,#ai-summary-output a").length'),0,'model HTML and outbound links are sanitized');
 assert.ok(await evaluate(tab,'document.querySelector("#ai-summary-output h1")'));
 assert.equal(await text('wiki-content'),before,'summary does not replace the article');
 await click('.ai-summary-sources summary');
 const source=await evaluate(tab,'document.querySelector(".ai-summary-sources a").href');assert.equal(new URL(source).searchParams.get('revision'),'1');assert.equal(new URL(source).hash,new URL(config.wiki).hash);
 await capture('summary-desktop');await click('.ai-summary-top button');
 await until(()=>evaluate(tab,'document.activeElement.id==="wiki-summary-page"'),'focus returns to summary control');
 const escapedBefore=await control({hold:true});await click('#wiki-summary-all');await writing();
 await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},tab.sessionId);
 await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},tab.sessionId);
 await until(()=>evaluate(tab,'!document.getElementById("ai-summary-dialog").open'),'Escape closes the summary');
 await until(async()=>(await control()).aborted>escapedBefore.aborted,'Escape cancels the provider');
 await control({hold:false});
 await click('#wiki-summary-all');await complete();assert.ok((await text('ai-summary-coverage')).includes('2 of 2 pages'));
 await click('.ai-summary-top button');
 // Touch input, cancellation, reduced motion, error and retry in the mobile UI.
 await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true},tab.sessionId);await cdp('Emulation.setTouchEmulationEnabled',{enabled:true},tab.sessionId);
 await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:'dark'},{name:'prefers-reduced-motion',value:'reduce'}]},tab.sessionId);
 const tap=async selector=>{const p=await evaluate(tab,'(()=>{const n=document.querySelector('+JSON.stringify(selector)+');n.scrollIntoView({block:"nearest"});const r=n.getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2};})()');await cdp('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[p]},tab.sessionId);await cdp('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]},tab.sessionId);};
 await control({hold:true});const previous=await control();await tap('#wiki-summary-page');await writing();
 assert.equal(await evaluate(tab,'getComputedStyle(document.querySelector(".ai-summary-piece")).animationName'),'none');
 assert.ok(await evaluate(tab,'document.documentElement.scrollWidth<=innerWidth && document.getElementById("ai-summary-dialog").scrollWidth<=document.getElementById("ai-summary-dialog").clientWidth'));
 await capture('summary-mobile');await tap('.ai-summary-actions button:first-child');
 await until(async()=>(await text('ai-summary-state')).startsWith('Stopped.'),'stopped');
 await until(async()=>(await control()).aborted>previous.aborted,'upstream cancellation');
 await control({hold:false});await tap('.ai-summary-actions button:nth-child(2)');await complete();
 await tap('.ai-summary-top button');
 await control({status:503});await tap('#wiki-summary-all');
 await until(async()=>(await text('ai-summary-state')).includes('unavailable'),'provider error displayed');
 assert.ok(!(await text('ai-summary-state')).includes('provider-private-detail'));
 await control({status:200});await tap('.ai-summary-actions button:nth-child(2)');await complete();
 assert.equal(await evaluate(tab,'document.getElementById("ai-summary-dialog").dataset.error'),'false');
 await tap('.ai-summary-top button');
 assert.deepEqual(await evaluate(tab,'testErrors'),[]);assert.deepEqual(await evaluate(tab,'testViolations'),[]);
 await cdp('Page.navigate',{url:config.chat},tab.sessionId);await until(()=>evaluate(tab,'!!document.getElementById("chat-summary") && !!document.querySelector("#log .msg")'),'chat ready');
 await tap('#chat-summary');await complete();assert.ok((await text('ai-summary-coverage')).includes('1 of 1 message'));
 assert.equal(await evaluate(tab,'document.querySelectorAll("#log .msg").length'),1);
 await click('.ai-summary-sources summary');await click('.ai-summary-sources a');
 assert.equal(await evaluate(tab,'location.hash'),new URL(config.chat).hash,'source navigation preserves the chat capability');
 assert.equal(await evaluate(tab,'document.getElementById("ai-summary-dialog").open'),false);
 assert.deepEqual(await evaluate(tab,'testErrors'),[]);assert.deepEqual(await evaluate(tab,'testViolations'),[]);
 console.log('Summary E2E passed: click-to-generate chat/page/wiki, incremental rendering, source revisions, desktop/mobile layouts, cancellation and upstream abort, retry, reduced motion, sanitized output, preserved content and CSP.');
}finally{chrome.kill('SIGTERM');await exited;}})().catch(error=>{console.error(error);process.exitCode=1;});`;
  const script=join(h.directory,'summary-browser.cjs');await writeFile(script,'const config='+JSON.stringify(config)+';\n'+harness+'\n'+exercise);
  const {stdout}=await execute(process.execPath,[script],{timeout:40000,maxBuffer:1024*1024});t.diagnostic(stdout);
  assert.equal(h.provider.requests.length,0,'summaries never use the Jev key');
});
