import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import { execute, page, post, wikiHarness } from './wiki-test-helper.mjs';

test('text attachments and chat code preview, copy full contents and download unchanged', {timeout:120000}, async t=>{
  assert.ok(process.env.CHROME_BIN,'Set CHROME_BIN for text preview browser tests');
  const h=await wikiHarness(t,{WIKI_BOOK_LAYOUT_ENABLED:'1'}), wiki=await h.create('Text previews');
  const json='{"id":90071992547409931234,"records":'+JSON.stringify(Array.from({length:30},(_,i)=>({name:'record '+i,ok:true,value:i})))+'}';
  const csv='name,value\n'+Array.from({length:119},(_,i)=>'row '+i+','+i).join('\n');
  const yaml='# deployment\nname: mayfly\nenabled: true\nreplicas: 3\n';
  const files=[['result.json',json],['table.csv',csv],['config.yaml',yaml],['invalid.json','{"broken":'],['binary.json',Buffer.from([255,0,10,128])],['long.log','x'.repeat(20000)],['notes.xml','<script>window.unsafeText=true</script>']];
  const attachments=[];
  for(const [name,body] of files) {
    const result=await wiki.request('/attachments',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':name},body});
    assert.equal(result.status,201,JSON.stringify(result.body));attachments.push(result.body);
  }
  const fenced='```typescript\n'+Array.from({length:65},(_,i)=>'const value'+i+' = '+i+';').join('\n')+'\n```';
  const saved=await wiki.request('/pages',post(page('Text outputs',attachments.map(f=>f.markdown).join('\n\n')+'\n\n'+fenced)));
  assert.equal(saved.status,201);
  const url=new URL(wiki.url);url.searchParams.set('page',saved.body.id);
  const downloads=join(h.directory,'downloads');await mkdir(downloads);
  const capture=process.env.MAYFLY_TEXT_CAPTURE_DIR;if(capture)await mkdir(capture,{recursive:true});
  const config={chrome:process.env.CHROME_BIN,profile:join(h.directory,'chrome'),url:url.href,base:h.base,json,csv,yaml,fenced,downloads,capture,jsonID:attachments[0].id};
  let harness=await readFile(new URL('../srv/testdata/chrome.cjs',import.meta.url),'utf8');
  harness=harness.replace('const msg=JSON.parse(raw), p=pending.get(msg.id);','const msg=JSON.parse(raw);if(msg.method==="Network.requestWillBeSent")requests.push(msg.params.request);const p=pending.get(msg.id);');
  const exercise=String.raw`
const fs=require('node:fs'),path=require('node:path');
(async()=>{try{
  const {targetInfos}=await cdp('Target.getTargets');const tab=await attach(targetInfos.find(t=>t.type==='page').targetId);
  await cdp('Network.enable',{},tab.sessionId);
  await cdp('Browser.grantPermissions',{origin:config.base,permissions:['clipboardReadWrite','clipboardSanitizedWrite']});
  await cdp('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:config.downloads});
  await cdp('Page.addScriptToEvaluateOnNewDocument',{source:'window.previewVisit=Math.random();window.previewErrors=[];window.previewCSP=[];addEventListener("error",e=>{if(e.message)previewErrors.push(e.message)});addEventListener("unhandledrejection",e=>previewErrors.push(String(e.reason)));addEventListener("securitypolicyviolation",e=>previewCSP.push(e.violatedDirective));'},tab.sessionId);
  const card=name=>'[...document.querySelectorAll(".mayfly-media")].find(c=>c.querySelector(".media-name").textContent==='+JSON.stringify(name)+')';
  const json=card('result.json');
  const click=async expression=>{
    await cdp('Page.bringToFront',{},tab.sessionId);
    const box=await evaluate(tab,'(()=>{const e='+expression+';e.scrollIntoView({block:"center"});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()');
    await cdp('Input.dispatchMouseEvent',{type:'mousePressed',button:'left',clickCount:1,...box},tab.sessionId);
    await cdp('Input.dispatchMouseEvent',{type:'mouseReleased',button:'left',clickCount:1,...box},tab.sessionId);
  };
  const lines=expression=>evaluate(tab,expression+'.querySelector("code").textContent.split("\\n").length');
  const copy=async(root,selector)=>{
    await click(root+'.querySelector(".media-copy > summary")');
    await click(root+'.querySelector('+JSON.stringify(selector)+')');
    await until(()=>evaluate(tab,root+'.querySelector(".text-copy-status").textContent.includes("copied")'),'clipboard write completed');
  };
  const shot=async name=>{if(config.capture){const {data}=await cdp('Page.captureScreenshot',{format:'png'},tab.sessionId);fs.writeFileSync(path.join(config.capture,name+'.png'),Buffer.from(data,'base64'));}};
  for(const mobile of [false,true]) {
    await cdp('Emulation.setDeviceMetricsOverride',{width:mobile?390:1440,height:mobile?844:1040,deviceScaleFactor:1,mobile},tab.sessionId);
    await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-color-scheme',value:mobile?'dark':'light'}]},tab.sessionId);
    const previousVisit=await evaluate(tab,'window.previewVisit');
    if(mobile)await cdp('Page.reload',{ignoreCache:true},tab.sessionId);
    else await cdp('Page.navigate',{url:config.url},tab.sessionId);
    await until(()=>evaluate(tab,'window.previewVisit!==undefined&&window.previewVisit!=='+JSON.stringify(previousVisit)),'fresh document');
    await until(()=>evaluate(tab,json+'?.querySelector(".text-source code")?.textContent.includes("90071992547409931234")'),'automatic JSON preview');
    assert.equal(await lines(json),50,'JSON starts at 50 formatted lines');
    assert.ok(await evaluate(tab,json+'.querySelectorAll(".wiki-code-property,.wiki-code-number,.wiki-code-keyword").length>3'),'JSON syntax highlighting');
    assert.ok(await evaluate(tab,json+'.querySelector(".text-coverage").textContent.includes("formatted")'));
    assert.equal(await evaluate(tab,json+'.querySelector(".text-expand").getAttribute("aria-expanded")'),'false');
    await click(json+'.querySelector(".media-copy > summary")');
    assert.ok(await evaluate(tab,'(()=>{const r='+json+'.querySelector(".media-copy-options").getBoundingClientRect();return r.left>=0&&r.right<=innerWidth})()'),'copy choices fit the viewport');
    await shot(mobile?'copy-menu-mobile-dark':'copy-menu-desktop-light');
    await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},tab.sessionId);
    await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape',windowsVirtualKeyCode:27},tab.sessionId);
    assert.equal(await evaluate(tab,json+'.querySelector(".media-copy").open'),false);
    assert.ok(await evaluate(tab,'document.activeElement==='+json+'.querySelector(".media-copy > summary")'),'Escape restores focus to Copy');
    await copy(json,'.text-copy-contents');
    assert.equal(await evaluate(tab,'navigator.clipboard.readText()'),config.json,'copy retains full compact original, including exact integer');
    await copy(json,'.text-copy-markdown');
    const copiedMarkdown=await evaluate(tab,'navigator.clipboard.readText()');
    assert.ok(copiedMarkdown.startsWith('**result\\.json**\n\n'+String.fromCharCode(96).repeat(3)+'json\n'));
    assert.ok(copiedMarkdown.includes('record 29')&&copiedMarkdown.includes('90071992547409931234'),'Markdown includes records beyond preview');
    await copy(json,'.text-copy-formatted');
    const rich=await evaluate(tab,'(async()=>{const [item]=await navigator.clipboard.read();return {types:item.types,text:await(await item.getType("text/plain")).text(),html:await(await item.getType("text/html")).text()}})()');
    assert.ok(rich.types.includes('text/html'));assert.ok(rich.html.includes('<strong>'));assert.ok(rich.text.includes('record 29'));
    assert.deepEqual(JSON.parse(rich.text),JSON.parse(config.json));
    await evaluate(tab,json+'.scrollIntoView({block:"start"})');await shot(mobile?'text-mobile-dark':'text-desktop-light');
    await click(json+'.querySelector(".text-expand")');
    assert.ok(await lines(json)>50,'expand reveals the remaining records');
    const expanded=await evaluate(tab,json+'.querySelector("code").textContent');
    assert.deepEqual(JSON.parse(expanded),JSON.parse(config.json));
    assert.ok(expanded.includes('90071992547409931234'),'large integer remains exact');
    assert.ok(await evaluate(tab,json+'.querySelector(".text-source").scrollHeight>'+json+'.querySelector(".text-source").clientHeight'),'expanded output scrolls');
    await click(json+'.querySelector(".text-expand")');assert.equal(await lines(json),50);
    await click(json+'.querySelector(".text-minimize")');
    assert.ok(await evaluate(tab,json+'.querySelector(".text-source").hidden'));
    assert.equal(await evaluate(tab,json+'.querySelector(".text-minimize").getAttribute("aria-expanded")'),'false');
    await click(json+'.querySelector(".text-minimize")');assert.equal(await lines(json),50);
    assert.ok(await evaluate(tab,'document.documentElement.scrollWidth<=innerWidth'),'no page overflow');
    const table=card('table.csv');await until(()=>evaluate(tab,table+'?.querySelector("code")'),'CSV preview');
    assert.equal(await lines(table),50);await click(table+'.querySelector(".text-expand")');
    assert.equal(await evaluate(tab,table+'.querySelector("code").textContent'),config.csv);
    await click(table+'.querySelector(".text-minimize")');await copy(table,'.text-copy-contents');
    assert.equal(await evaluate(tab,'navigator.clipboard.readText()'),config.csv,'minimized preview still copies all lines');
    const yaml=card('config.yaml');await until(()=>evaluate(tab,yaml+'?.querySelector("code")'),'YAML preview');
    assert.equal(await evaluate(tab,yaml+'.querySelector("code").textContent'),config.yaml.trimEnd());
    assert.ok(await evaluate(tab,yaml+'.querySelectorAll(".wiki-code-comment,.wiki-code-keyword").length>0'));
    assert.ok(await evaluate(tab,yaml+'.querySelector(".text-expand").hidden'),'short files need no expansion');
    await until(()=>evaluate(tab,card('binary.json')+'?.querySelector(".media-status").textContent.includes("preview unavailable")'),'binary fallback');
    assert.equal(await evaluate(tab,card('binary.json')+'.querySelector("code")'),null);
    assert.equal(await evaluate(tab,card('invalid.json')+'.querySelector("code").textContent'),'{"broken":');
    assert.equal(await evaluate(tab,card('notes.xml')+'.querySelector("code").textContent'),'<script>window.unsafeText=true</script>');
    assert.equal(await evaluate(tab,'window.unsafeText'),undefined);
    await copy(card('notes.xml'),'.text-copy-formatted');
    const safe=await evaluate(tab,'(async()=>{const [item]=await navigator.clipboard.read();return (await item.getType("text/html")).text()})()');
    assert.ok(safe.includes('&lt;script&gt;'));assert.ok(!safe.includes('<script>'));
    const long=card('long.log');assert.equal((await evaluate(tab,long+'.querySelector("code").textContent')).length,16384);
    await click(long+'.querySelector(".text-expand")');assert.equal((await evaluate(tab,long+'.querySelector("code").textContent')).length,20000);
    const code='document.querySelector("#wiki-content > .mayfly-text")';assert.equal(await lines(code),50);
    assert.ok(await evaluate(tab,code+'.querySelector(".wiki-code-keyword")!==null'));
    await click(code+'.querySelector(".text-expand")');assert.equal(await lines(code),65);
    await click(code+'.querySelector(".text-minimize")');assert.ok(await evaluate(tab,code+'.querySelector("pre").hidden'));
    assert.deepEqual(await evaluate(tab,'previewErrors'),[]);assert.deepEqual(await evaluate(tab,'previewCSP'),[]);
  }
  await evaluate(tab,'window.originalClipboard=navigator.clipboard;Object.defineProperty(navigator,"clipboard",{configurable:true,value:{write:()=>Promise.reject(new DOMException("Denied","NotAllowedError"))}})');
  await click(json+'.querySelector(".media-copy > summary")');await click(json+'.querySelector(".text-copy-contents")');
  await until(()=>evaluate(tab,json+'.querySelector(".text-copy-status").textContent.includes("Copy unavailable")'),'denied clipboard fallback');
  assert.equal(await evaluate(tab,json+'.querySelector(".text-copy-contents").disabled'),false);
  await evaluate(tab,'Object.defineProperty(navigator,"clipboard",{configurable:true,value:{writeText:value=>originalClipboard.writeText(value)}})');
  await copy(json,'.text-copy-formatted');
  assert.equal(await evaluate(tab,json+'.querySelector(".text-copy-status").textContent'),'Contents copied as plain text.');
  await evaluate(tab,'Object.defineProperty(navigator,"clipboard",{configurable:true,value:undefined})');
  await click(json+'.querySelector(".media-copy > summary")');await click(json+'.querySelector(".text-copy-contents")');
  await until(()=>evaluate(tab,json+'.querySelector(".text-copy-status").textContent.includes("Copy unavailable")'),'unsupported clipboard fallback');
  await click(json+'.querySelector(".media-download")');
  await until(()=>fs.existsSync(path.join(config.downloads,'result.json')),'JSON downloaded');
  assert.equal(fs.readFileSync(path.join(config.downloads,'result.json'),'utf8'),config.json,'download retains compact original bytes');
  assert.equal(requests.filter(r=>r.method==='GET'&&r.url.includes('/attachments/'+config.jsonID)).length,2,'one authenticated GET per page visit; expand and download reuse bytes');
  assert.deepEqual(await evaluate(tab,'previewErrors'),[]);
  console.log('PASS wiki text: full raw/Markdown/rich clipboard, safe markup, minimized copy, denied/unsupported fallback, exact downloads, shared requests, desktop/light and mobile/dark');
  await cdp('Page.navigate',{url:config.base+'/'},tab.sessionId);
  await until(()=>evaluate(tab,'typeof newChannel==="function"'),'chat creation');await click('document.getElementById("newbtn")');
  await until(()=>evaluate(tab,'!!document.getElementById("compose")&&!document.getElementById("main").hidden'),'chat ready');
  await evaluate(tab,'document.getElementById("text").value='+JSON.stringify(config.fenced)+';document.getElementById("compose").requestSubmit()');
  const code='document.querySelector("#log .mayfly-text")';
  await until(()=>evaluate(tab,'!!'+code),'chat code preview');assert.equal(await lines(code),50);
  await click(code+'.querySelector(".text-expand")');assert.equal(await lines(code),65);
  await click(code+'.querySelector(".text-minimize")');assert.ok(await evaluate(tab,code+'.querySelector("pre").hidden'));
  await click(code+'.querySelector(".text-minimize")');assert.equal(await lines(code),50);
  await copy(code,'.text-copy-contents');
  assert.ok((await evaluate(tab,'navigator.clipboard.readText()')).includes('const value64 = 64;'));
  // Exercise a real paste into an editor, beyond reading clipboard API output.
  await evaluate(tab,'window.pasteTarget=document.createElement("textarea");document.body.append(pasteTarget);pasteTarget.focus()');
  await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'v',code:'KeyV',modifiers:2,windowsVirtualKeyCode:86},tab.sessionId);
  await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'v',code:'KeyV',modifiers:2,windowsVirtualKeyCode:86},tab.sessionId);
  await until(()=>evaluate(tab,'pasteTarget.value.includes("const value64 = 64;")'),'real paste of full chat code');
  await evaluate(tab,'pasteTarget.remove()');
  assert.ok(await evaluate(tab,code+'.querySelector(".wiki-code-keyword")!==null'));
  assert.ok(await evaluate(tab,'document.documentElement.scrollWidth<=innerWidth'));
  assert.deepEqual(await evaluate(tab,'previewErrors'),[]);assert.deepEqual(await evaluate(tab,'previewCSP'),[]);
  console.log('PASS chat: full code copy and real editor paste, highlighting and accessible preview controls');
}finally{chrome.kill('SIGTERM');await exited;}})().catch(error=>{console.error(error);process.exitCode=1;});`;
  const script=join(h.directory,'text-preview.cjs');await writeFile(script,'const config='+JSON.stringify(config)+';\nconst requests=[];\n'+harness+'\n'+exercise);
  try {const {stdout}=await execute(process.execPath,[script],{timeout:90000,maxBuffer:1024*1024});t.diagnostic(stdout);}
  catch(error){throw new Error((error.stdout||'')+(error.stderr||error.message));}
});
