import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import test from 'node:test';
import { execute, wikiHarness } from './wiki-test-helper.mjs';

test('Chrome and the downloaded agent client share the complete wiki workflow', {timeout:90000}, async t=>{
  assert.ok(process.env.CHROME_BIN,'Set CHROME_BIN to run the real wiki browser test');
  const h=await wikiHarness(t,{JEV_WIKI_SEARCH_ENABLED:'1',TYPESAFE_API_KEY:'fixture-key'});
  const client=join(h.directory,'wiki.mjs');await writeFile(client,(await h.http('/static/wiki.mjs')).body);
  const agentFile=join(h.directory,'agent.md');await writeFile(agentFile,'# Operations\n\n## Recovery\nAgent updated the recovery instructions.\n');
  const secondFile=join(h.directory,'fencing.md');await writeFile(secondFile,'# Fencing\n\nAvoid split brain during ownership transfer.\n');
  const png=join(h.directory,'diagram.png');await writeFile(png,Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aS1sAAAAASUVORK5CYII=','base64'));
  const config={chrome:process.env.CHROME_BIN,profile:join(h.directory,'chrome'),base:h.base,client,agentFile,secondFile,png};
  let harness=await readFile(new URL('../srv/testdata/chrome.cjs',import.meta.url),'utf8');
  harness=harness.replace('const msg=JSON.parse(raw), p=pending.get(msg.id);','const msg=JSON.parse(raw); if(msg.method === "Network.requestWillBeSent") browserRequests.push(msg.params.request.url); const p=pending.get(msg.id);');
  const exercise=String.raw`
const execFile=require('node:util').promisify(require('node:child_process').execFile);
async function agent(...args){const {stdout}=await execFile(process.execPath,[config.client,...args],{timeout:20000});return JSON.parse(stdout);}
const browserRequests=[];
(async()=>{
 try {
  const {targetInfos}=await cdp('Target.getTargets');const tab=await attach(targetInfos.find(t=>t.type==='page').targetId);
  await cdp('Network.enable',{},tab.sessionId);
  await cdp('Page.addScriptToEvaluateOnNewDocument',{source:"window.testErrors=[];window.testViolations=[];window.addEventListener('error',e=>testErrors.push(e.message));window.addEventListener('unhandledrejection',e=>testErrors.push(String(e.reason)));window.addEventListener('securitypolicyviolation',e=>testViolations.push(e.violatedDirective));"},tab.sessionId);
  await cdp('Page.navigate',{url:config.base+'/'},tab.sessionId);
  await until(()=>evaluate(tab,"!!document.getElementById('newwikibtn') && document.getElementById('newwikibtn').checkVisibility()"),'wiki entry on home page');
  await evaluate(tab,"document.getElementById('newwikibtn').click()");
  await until(()=>evaluate(tab,"!!document.getElementById('wiki-create') && !document.getElementById('wiki-create').hidden"),'creation form');
  await evaluate(tab,"document.getElementById('wiki-create-title').value='Shared operations';document.querySelector('#wiki-create button').click()");
  await until(()=>evaluate(tab,"!!document.getElementById('wiki-main') && !document.getElementById('wiki-main').hidden"),'created wiki');
  const url=await evaluate(tab,'location.href');assert.match(url,/\/w\/.+#.+/);
  assert.equal((await agent('read',url)).title,'Shared operations');
  const set=(id,value)=>evaluate(tab,'document.getElementById('+JSON.stringify(id)+').value='+JSON.stringify(value));
  const click=id=>evaluate(tab,'document.getElementById('+JSON.stringify(id)+').click()');
  await click('wiki-new-page');await set('wiki-page-title','Operations');await set('wiki-page-path','operations');
  const original='Operations\n==========\n\n## Recovery\nHuman recovery notes.\n\n~~~typescript\nconst healthy = true;\n~~~\n\n<script>window.wikiUnsafe=true</script>\n\n![external](https://example.invalid/never-load.png)\n';
  await set('wiki-markdown',original);await evaluate(tab,"document.querySelector('#wiki-editor button[type=submit]').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-status').textContent==='Page saved.'"),'first page saved');
  const firstID=await evaluate(tab,"new URLSearchParams(location.search).get('page')");
  assert.equal((await agent('read',url,firstID)).markdown,original);
  assert.equal(await evaluate(tab,'window.wikiUnsafe'),undefined);
  assert.ok(await evaluate(tab,"document.querySelectorAll('#wiki-content .wiki-code-keyword').length>0"));
  assert.ok(await evaluate(tab,"document.getElementById('wiki-content').textContent.includes('<script>')"));
  assert.equal(await evaluate(tab,"document.querySelector('#wiki-content #s4').childNodes[0].textContent"),'Recovery');
  assert.equal(await evaluate(tab,"document.querySelector('#wiki-content h1').querySelector('button')"),null,'An underlined title must not steal the next section anchor');
  const second=await agent('new-page',url,'fencing','Fencing',config.secondFile);assert.equal(second.revision,1);
  await set('wiki-comment-anchor','Recovery');await set('wiki-comment-body','Check the partition case.');
  await evaluate(tab,"document.querySelector('#wiki-comment-form button').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-comments').textContent.includes('Check the partition case.')"),'section comment');
  await evaluate(tab,"[...document.querySelector('#wiki-comments article').querySelectorAll('button')].find(b=>b.textContent==='Reply').click()");
  await evaluate(tab,"document.querySelector('#wiki-comments form textarea').value='Confirmed: fencing runs before recovery.';document.querySelector('#wiki-comments form button').click()");
  await until(()=>evaluate(tab,"document.querySelector('#wiki-comments article > article.reply .comment-body')?.textContent==='Confirmed: fencing runs before recovery.'"),'reply grouped under its thread');
  await evaluate(tab,"[...document.querySelector('#wiki-comments article').querySelectorAll('button')].find(b=>b.textContent==='Resolve').click()");
  await until(()=>evaluate(tab,"[...document.querySelector('#wiki-comments article').querySelectorAll('button')].some(b=>b.textContent==='Reopen')"),'thread resolved');
  await agent('comment',url,firstID,'Agent reviewed this section.','Recovery');
  await click('wiki-edit');await until(()=>evaluate(tab,"!document.getElementById('wiki-editor').hidden"),'editing page');
  await set('wiki-markdown',original+'\nHuman draft still here.');
  const updated=await agent('write',url,firstID,'1',config.agentFile);assert.equal(updated.revision,2);
  await evaluate(tab,"document.querySelector('#wiki-editor button[type=submit]').click()");
  await until(()=>evaluate(tab,"!document.getElementById('wiki-conflict').hidden"),'conflict shown');
  assert.ok(await evaluate(tab,"document.getElementById('wiki-markdown').value.includes('Human draft still here.')"));
  assert.ok(await evaluate(tab,"document.getElementById('wiki-conflict-current').textContent.includes('Agent updated')"));
  await set('wiki-markdown',updated.markdown+'\nHuman merged draft.');await click('wiki-conflict-merge');
  await evaluate(tab,"document.querySelector('#wiki-editor button[type=submit]').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-status').textContent==='Page saved.'"),'merged page saved');
  assert.equal((await agent('read',url,firstID)).revision,3);
  assert.ok(await evaluate(tab,"document.getElementById('wiki-comments').textContent.includes('Agent reviewed this section.')"));
  await click('wiki-history-button');await until(()=>evaluate(tab,"document.querySelectorAll('#wiki-history button').length===3"),'history visible');
  await evaluate(tab,"[...document.querySelectorAll('#wiki-history button')].find(b=>b.textContent.startsWith('Revision 1 ')).click()");
  await until(()=>evaluate(tab,"!document.getElementById('wiki-restore').hidden"),'historical snapshot');
  await click('wiki-restore');await until(()=>evaluate(tab,"!document.getElementById('wiki-editor').hidden"),'restore draft');
  await evaluate(tab,"document.querySelector('#wiki-editor button[type=submit]').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-status').textContent==='Page saved.'"),'restored page saved');
  const restored=await agent('read',url,firstID);assert.equal(restored.revision,4);assert.equal(restored.markdown,original);
  assert.match((await agent('read',url,firstID,'3')).markdown,/Human merged draft/);
  await click('wiki-edit');await until(()=>evaluate(tab,"!document.getElementById('wiki-editor').hidden"),'image draft');
  const {root}=await cdp('DOM.getDocument',{},tab.sessionId);
  const {nodeId}=await cdp('DOM.querySelector',{nodeId:root.nodeId,selector:'#wiki-upload'},tab.sessionId);
  await cdp('DOM.setFileInputFiles',{nodeId,files:[config.png]},tab.sessionId);
  await until(()=>evaluate(tab,"document.getElementById('wiki-markdown').value.includes('attachment:')"),'owned image inserted');
  await evaluate(tab,"document.querySelector('#wiki-editor button[type=submit]').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-status').textContent==='Page saved.'"),'page with image saved');
  await until(()=>evaluate(tab,"[...document.querySelectorAll('#wiki-content img')].some(i=>i.complete&&i.naturalWidth===1)"),'authorized image rendered');
  await set('wiki-query','fencing');await evaluate(tab,"document.querySelector('#wiki-search-form button[type=submit]').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-results').textContent.includes('Fencing')"),'keyword search');
  await evaluate(tab,"document.querySelector('#wiki-results a').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-page-meta').textContent.startsWith('fencing')"),'search citation opened');
  await set('wiki-query','Recovery');await set('wiki-search-mode','relevance');await set('wiki-context','Preserve acknowledged writes');
  await evaluate(tab,"document.getElementById('wiki-search-mode').dispatchEvent(new Event('change'));document.querySelector('#wiki-search-form button[type=submit]').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-results').textContent.includes('Ranked by Jev')"),'Jev search');
  assert.ok((await agent('search',url,JSON.stringify({query:'Recovery',mode:'relevance'}))).results.length);
  assert.ok((await agent('changes',url,'0')).changes.some(c=>c.kind==='comment_created'));
  await click('wiki-agent');assert.ok(await evaluate(tab,"document.getElementById('wiki-agent-text').value.includes('node wiki.mjs read')"));
  await evaluate(tab,"document.getElementById('wiki-agent-dialog').close()");
  await cdp('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:false},tab.sessionId);
  assert.ok(await evaluate(tab,'document.documentElement.scrollWidth<=window.innerWidth'),'mobile overflow');
  assert.deepEqual(await evaluate(tab,'testErrors'),[],'browser errors');assert.deepEqual(await evaluate(tab,'testViolations'),[],'CSP violations');
  assert.ok(!browserRequests.some(u=>u.includes('example.invalid')),'external image must not load automatically');
  const guest=await attach((await cdp('Target.createTarget',{url:'about:blank'})).targetId);
  await cdp('Page.navigate',{url:url.split('#')[0]},guest.sessionId);
  await until(()=>evaluate(guest,"!!document.getElementById('wiki-status') && document.getElementById('wiki-status').textContent.includes('missing its key')"),'missing key message');
  assert.equal(await evaluate(guest,"document.getElementById('wiki-main').hidden"),true);
  await cdp('Target.activateTarget',{targetId:tab.targetId});
  await click('wiki-delete');await evaluate(tab,"document.querySelector('#wiki-delete-dialog button[value=delete]').click()");
  await until(()=>evaluate(tab,"document.getElementById('wiki-status').textContent==='Wiki deleted.'"),'wiki deletion').catch(async error=>{console.error(await evaluate(tab,"({status:document.getElementById('wiki-status').textContent,open:document.getElementById('wiki-delete-dialog').open,value:document.getElementById('wiki-delete-dialog').returnValue,errors:testErrors,violations:testViolations})"));throw error;});
  assert.deepEqual(await evaluate(tab,'testErrors'),[]);assert.deepEqual(await evaluate(tab,'testViolations'),[]);
  console.log('Wiki E2E: browser creation, agent reads/writes, CAS conflict and merge, history restoration, comments, R2 image rendering, local/Jev search, citations, mobile layout, missing key, CSP and deletion passed.');
 }finally{chrome.kill('SIGTERM');await exited;}
})().catch(error=>{console.error(error);process.exitCode=1;});
`;
  const script=join(h.directory,'browser.cjs');await writeFile(script,`const config=${JSON.stringify(config)};\n${harness}\n${exercise}`);
  const {stdout}=await execute(process.execPath,[script],{timeout:70000,maxBuffer:1024*1024});t.diagnostic(stdout);
  assert.ok(h.provider.requests.length>0,'Jev fixture was exercised from browser and agent');
});
