import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import test from 'node:test';
import { execute } from './wiki-test-helper.mjs';

test('wiki validation, section boundaries and bounded relevance adapter',async t=>{
  const dir=await mkdtemp(join(tmpdir(),'wiki-unit-'));t.after(()=>rm(dir,{recursive:true,force:true}));
  const load=async name=>{const file=join(dir,name+'.mjs');await execute('esbuild',[new URL('./native/'+name+'.ts',import.meta.url).pathname,'--bundle','--platform=neutral','--format=esm','--outfile='+file]);return import(pathToFileURL(file));};
  const core=await load('wiki-core'),{rankPassages}=await load('wiki-search');
  assert.equal(core.attachmentType('text/html',Buffer.from('<script>bad()</script>')),'application/octet-stream');
  assert.equal(core.attachmentType('image/svg+xml',Buffer.from('<?xml version="1.0"?><svg xmlns="http://www.w3.org/2000/svg"/>')),'image/svg+xml');
  assert.throws(()=>core.attachmentType('image/svg+xml',Buffer.from('<html><svg/></html>')),/signature/);
  assert.throws(()=>core.attachmentType('image/svg+xml',Buffer.from('<!DOCTYPE svg><svg/>')),/signature/);
  assert.throws(()=>core.attachmentType('image/svg+xml',Buffer.from([0xff,0xfe,0x3c])),/UTF-8/);
  assert.equal(core.attachmentType('video/webm',Buffer.from('1a45dfa301','hex')),'video/webm');
  assert.equal(core.attachmentType('video/ogg',Buffer.from('OggSfixture')),'video/ogg');
  for(const type of ['image/png','image/jpeg','image/gif','image/webp','video/mp4','video/webm','video/ogg'])assert.throws(()=>core.attachmentType(type,Buffer.from('<html>')),/signature/);
  assert.deepEqual(core.wikiSettings({}),{enabled:false,relevance:false,layout:'classic'});
  assert.deepEqual(core.wikiSettings({WIKI_ENABLED:'1',JEV_WIKI_SEARCH_ENABLED:'1'}),{enabled:true,relevance:true,layout:'classic'});
  assert.deepEqual(core.wikiSettings({WIKI_ENABLED:'1',ENCRYPTION_ENABLED:'1',JEV_WIKI_SEARCH_ENABLED:'invalid'}),{enabled:false,relevance:false,layout:'classic'});
  for(const flag of ['true','false','', '2'])assert.throws(()=>core.wikiSettings({WIKI_ENABLED:flag}));
  assert.throws(()=>core.wikiSettings({WIKI_ENABLED:'1',JEV_WIKI_SEARCH_ENABLED:'true'}));
  assert.equal(core.wikiSettings({WIKI_ENABLED:'1',WIKI_BOOK_LAYOUT_ENABLED:'1'}).layout,'book');
  assert.equal(core.wikiSettings({WIKI_ENABLED:'0',WIKI_BOOK_LAYOUT_ENABLED:'invalid'}).layout,'classic');
  assert.throws(()=>core.wikiSettings({WIKI_ENABLED:'1',WIKI_BOOK_LAYOUT_ENABLED:'true'}));
  assert.equal(core.text('emoji 🌱','text',30),'emoji 🌱');assert.throws(()=>core.text('\ud800','text',30));
  const markdown='Intro\n# Main\nText\n```md\n## Not a heading\n```\n## Real section\nLast line';
  const parts=core.sections(markdown);assert.deepEqual(parts.map(s=>s.heading),['Introduction','Main','Real section']);assert.equal(parts[2].start_line,7);assert.equal(parts[2].end_line,8);assert.match(parts[1].body,/Not a heading/);
  const longLine='x'+'🌱'.repeat(6000),longParts=core.sections(longLine);
  assert.ok(longParts.map(s=>s.body).join('')===longLine,'Long-line passages must preserve Unicode source text');
  assert.ok(longParts.every(s=>s.body.length<=4000&&s.start_line===1&&s.end_line===1&&s.body.isWellFormed()));
  assert.ok(core.sections('before\n'+longLine+'\nafter').every(s=>s.start_line>=1&&s.end_line>=s.start_line&&s.end_line<=3));
  assert.throws(()=>core.pageInput({title:'Long heading',path:'long-heading',markdown:'# '+'🌱'.repeat(126)}),/500 UTF-8 bytes/);
  assert.throws(()=>core.commentAnchor({type:'section',heading:'Same',revision:1},1,'# Same\nA\n# Same\nB'));
  assert.throws(()=>core.commentAnchor({type:'page',revision:1},2,'Body'));
  const input=core.searchInput({query:'node failure',related_terms:['leases'],context:'Recover service',mode:'relevance'});
  assert.equal(core.matchQuery(input),'"node" OR "failure" OR "leases"');
  assert.throws(()=>core.searchInput({query:'x',mode:'unknown'}));assert.throws(()=>core.searchInput({query:'x',limit:-1}));
  const hits=[0,1].map(i=>({page_id:'private-'+i,revision:1,title:'Page '+i,path:'path-'+i,section:'s1',heading:'Heading',start_line:1,end_line:3,excerpt:'Source passage '+i,url:'/w/private?key=never-send'}));
  const env={TYPESAFE_API_KEY:'fixture-key',TYPESAFE_MODEL:'fixture-model'};
  let sent;
  const response=answers=>new Response(JSON.stringify({model:'fixture',answers}),{headers:{'Content-Type':'application/json'}});
  const good={passage_0:{type:'score',score:1,confidence:0.99},passage_1:{type:'score',score:2.8,confidence:0.6}};
  const ranked=await rankPassages(input,hits,env,async(url,init)=>{sent=JSON.parse(init.body);assert.equal(init.redirect,'error');assert.equal(init.headers.Authorization,'Bearer fixture-key');return response(good);});
  assert.equal(ranked[0].page_id,'private-1');assert.equal(ranked[0].confidence,0.6);assert.doesNotMatch(JSON.stringify(sent),/private|never-send|fixture-key/);
  assert.equal(sent.model,'fixture-model');assert.equal(sent.questions.passage_1.type,'score');assert.match(sent.questions.passage_1.instructions,/candidates\[1\]/);
  for(const invalid of [NaN,Infinity,-1,4,'2',null])assert.equal(await rankPassages(input,hits,env,async()=>response({...good,passage_1:{...good.passage_1,score:invalid}})),null);
  assert.equal(await rankPassages(input,hits,env,async()=>response({passage_0:good.passage_0})),null);
  assert.equal(await rankPassages(input,hits,env,async()=>new Response('x'.repeat(65537))),null);
  assert.equal(await rankPassages(input,hits,{},()=>assert.fail('Disabled credentials must not call provider')),null);
  const before=Date.now();assert.equal(await rankPassages(input,hits,env,()=>new Promise(()=>{})),null);assert.ok(Date.now()-before<2000);
});
